services:
  - type: web
    name: tc_app
    env: python
    plan: free
    buildCommand: "./bin/render_compile.sh"
    startCommand: "gunicorn wsgi:application --config './config/gunicorn.conf'"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tc_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: TAB_DIRECTOR_EMAIL
        sync: false
      - key: TIME_ZONE
        sync: false
  - type: pserv
    name: tc_redis
    env: docker
    repo: https://github.com/render-examples/redis.git # optional
    envVars:
      - key: GENERATED_SECRET
        generateValue: true # will generate a base64-encoded 256-bit secret
      - key: DASHBOARD_SECRET
        generateValue: true # will generate a base64-encoded 256-bit secret
    disk:
      name: redis-data
      mountPath: /var/lib/redis
      sizeGB: 1 # optional

databases:
  - name: tc_db
    databaseName: tabbycat
    user: tabbycat
    plan: free
