services:
  - type: web
    name: tabbycat
    env: python
    plan: free
    buildCommand: "./bin/render_compile.sh"
    startCommand: "npm run serve-render"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tc_db
          property: connectionString
      - key: REDIS_HOSTNAME
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: TAB_DIRECTOR_EMAIL
        sync: false
      - key: TIME_ZONE
        sync: false

databases:
  - name: tc_db
    databaseName: tabbycat
    user: tabbycat
    plan: free
